### PR TITLE
Update __main__.py

### PR DESCRIPTION
**Pull request by krishna6688**
...

### CODE REVIEW

**Comment by legendx22** [comment]
Bro aapne galat jaga dedi pull request

**Comment by krishna6688** [comment]
Oooo

**Comment by legendx22** [comment]
Plzz changes on your repo 🥰

**Comment by krishna6688** [comment]
Okkk😅

**Comment by legendx22** [comment]
Hmm

**Comment by krishna6688** [comment]
Ok👍

**Comment by legendx22** [comment]
Telegram username ?

**Comment by krishna6688** [comment]
I will msg you

**Comment by legendx22** [comment]
Abhi m telegram ni jaa skta

**Comment by legendx22** [comment]
Yahi bata do

**Pull request closed without merging**
